/**
 * Manufacturers and their models for the vehicle form: the current lineups (model year 2026) and the models of the
 * last years a workshop still sees. Not complete on purpose: any other manufacturer or model can be typed in.
 */
export const VEHICLE_MODELS: Record<string, string[]> = {
  'Acura': ['ADX', 'Integra', 'TLX', 'RDX', 'MDX', 'ZDX', 'NSX', 'ILX', 'RLX', 'TSX', 'TL', 'RL', 'RSX'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', 'Junior', '4C', 'Giulietta', 'MiTo', '159', 'Brera', 'Spider'],
  'Aston Martin': ['DB12', 'DBX', 'Vantage', 'Vanquish', 'DBS', 'DB11', 'Rapide', 'Valkyrie'],
  'Audi': ['A3', 'S3', 'RS 3', 'A4', 'S4', 'RS 4', 'A5', 'S5', 'RS 5', 'A6', 'S6', 'RS 6', 'A7', 'S7', 'RS 7', 'A8', 'S8',
    'Q3', 'RS Q3', 'Q4 e-tron', 'Q5', 'SQ5', 'Q6 e-tron', 'Q7', 'SQ7', 'Q8', 'SQ8', 'RS Q8', 'Q8 e-tron', 'e-tron GT', 'RS e-tron GT',
    'TT', 'R8', 'A1', 'Q2', 'allroad'],
  'Bentley': ['Bentayga', 'Continental GT', 'Continental GTC', 'Flying Spur', 'Mulsanne'],
  'BMW': ['1 Series', '2 Series', '2 Series Gran Coupe', '3 Series', '4 Series', '4 Series Gran Coupe', '5 Series', '6 Series', '7 Series', '8 Series',
    'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'Z4', 'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'iX1', 'iX3',
    'M2', 'M3', 'M4', 'M5', 'M8', 'X3 M', 'X4 M', 'X5 M', 'X6 M'],
  'Bugatti': ['Chiron', 'Veyron', 'Tourbillon'],
  'Buick': ['Encore', 'Encore GX', 'Envista', 'Envision', 'Enclave', 'LaCrosse', 'Regal', 'Verano', 'Cascada', 'Lucerne'],
  'BYD': ['Atto 3', 'Dolphin', 'Seal', 'Seal U', 'Han', 'Tang', 'Song Plus', 'Qin Plus', 'Yuan Plus', 'Shark'],
  'Cadillac': ['CT4', 'CT5', 'CT6', 'XT4', 'XT5', 'XT6', 'Escalade', 'Escalade ESV', 'Escalade IQ', 'Lyriq', 'Optiq', 'Vistiq', 'Celestiq',
    'ATS', 'CTS', 'XTS', 'SRX', 'ELR', 'DTS', 'STS'],
  'Chery': ['Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Omoda 5'],
  'Chevrolet': ['Spark', 'Sonic', 'Cruze', 'Malibu', 'Impala', 'Camaro', 'Corvette', 'Bolt EV', 'Bolt EUV', 'Volt',
    'Trax', 'Trailblazer', 'Equinox', 'Equinox EV', 'Blazer', 'Blazer EV', 'Traverse', 'Tahoe', 'Suburban',
    'Colorado', 'Silverado 1500', 'Silverado 2500HD', 'Silverado 3500HD', 'Silverado EV', 'Express', 'City Express',
    'Orlando', 'Aveo', 'Cobalt', 'HHR', 'Avalanche', 'Captiva Sport', 'Uplander'],
  'Chrysler': ['300', 'Pacifica', 'Voyager', 'Grand Caravan', '200', 'Town & Country', 'Sebring', 'PT Cruiser', 'Aspen'],
  'Citroën': ['C1', 'C3', 'C3 Aircross', 'C4', 'C4 X', 'C5 Aircross', 'C5 X', 'Berlingo', 'SpaceTourer', 'Jumpy', 'Jumper', 'C-Elysée'],
  'Cupra': ['Born', 'Formentor', 'Leon', 'Ateca', 'Tavascan', 'Terramar'],
  'Dacia': ['Sandero', 'Sandero Stepway', 'Logan', 'Duster', 'Jogger', 'Spring', 'Bigster'],
  'Daihatsu': ['Mira', 'Tanto', 'Move', 'Terios', 'Rocky', 'Sirion'],
  'Dodge': ['Charger', 'Challenger', 'Durango', 'Hornet', 'Journey', 'Grand Caravan', 'Dart', 'Avenger', 'Caliber', 'Viper', 'Nitro', 'Dakota'],
  'DS': ['DS 3', 'DS 4', 'DS 7', 'DS 9'],
  'Ferrari': ['296 GTB', '296 GTS', 'SF90 Stradale', '812 Superfast', 'Roma', 'Purosangue', '12Cilindri', 'F8 Tributo', 'Portofino', '488', 'California', 'GTC4Lusso'],
  'Fiat': ['500', '500e', '500X', '500L', '600e', '124 Spider', 'Panda', 'Tipo', 'Punto', 'Doblò', 'Ducato'],
  'Ford': ['Fiesta', 'Focus', 'Fusion', 'Taurus', 'Mustang', 'Mustang Mach-E', 'GT', 'EcoSport', 'Escape', 'Bronco', 'Bronco Sport',
    'Edge', 'Explorer', 'Flex', 'Expedition', 'Ranger', 'Maverick', 'F-150', 'F-150 Lightning', 'F-250 Super Duty', 'F-350 Super Duty',
    'F-450 Super Duty', 'Transit', 'Transit Connect', 'E-Series', 'C-Max', 'Crown Victoria', 'Five Hundred', 'Freestyle',
    'Kuga', 'Puma', 'S-Max', 'Galaxy', 'Mondeo', 'Ka'],
  'Geely': ['Coolray', 'Monjaro', 'Emgrand', 'Geometry C'],
  'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'Electrified G80', 'Electrified GV70'],
  'GMC': ['Terrain', 'Acadia', 'Yukon', 'Yukon XL', 'Canyon', 'Sierra 1500', 'Sierra 2500HD', 'Sierra 3500HD', 'Sierra EV', 'Hummer EV', 'Savana', 'Envoy'],
  'Great Wall': ['Haval H6', 'Haval Jolion', 'Poer', 'Tank 300'],
  'Honda': ['Fit', 'Civic', 'Civic Type R', 'Insight', 'Accord', 'Clarity', 'HR-V', 'CR-V', 'ZR-V', 'Passport', 'Pilot', 'Odyssey', 'Ridgeline',
    'Prologue', 'CR-Z', 'Element', 'Crosstour', 'S2000', 'Jazz', 'e'],
  'Hummer': ['H2', 'H3'],
  'Hyundai': ['Accent', 'Elantra', 'Elantra N', 'Sonata', 'Veloster', 'Ioniq', 'Ioniq 5', 'Ioniq 5 N', 'Ioniq 6', 'Ioniq 9', 'Venue', 'Kona',
    'Kona Electric', 'Tucson', 'Santa Cruz', 'Santa Fe', 'Palisade', 'Nexo', 'Genesis Coupe', 'Azera', 'Entourage', 'Veracruz',
    'i10', 'i20', 'i30', 'Bayon'],
  'Ineos': ['Grenadier'],
  'Infiniti': ['Q50', 'Q60', 'QX50', 'QX55', 'QX60', 'QX80', 'Q70', 'QX30', 'QX70', 'G37', 'M37', 'EX35', 'FX35', 'JX35'],
  'Isuzu': ['D-Max', 'MU-X', 'NPR', 'Rodeo', 'Trooper', 'Ascender'],
  'Jaguar': ['E-Pace', 'F-Pace', 'I-Pace', 'F-Type', 'XE', 'XF', 'XJ', 'XK', 'S-Type', 'X-Type'],
  'Jeep': ['Wrangler', 'Wrangler 4xe', 'Gladiator', 'Compass', 'Renegade', 'Cherokee', 'Grand Cherokee', 'Grand Cherokee L', 'Grand Cherokee 4xe',
    'Wagoneer', 'Grand Wagoneer', 'Wagoneer S', 'Recon', 'Avenger', 'Patriot', 'Liberty', 'Commander'],
  'Kia': ['Rio', 'Forte', 'K4', 'K5', 'Optima', 'Stinger', 'Soul', 'Niro', 'Niro EV', 'Seltos', 'Sportage', 'Sorento', 'Telluride', 'Carnival', 'Sedona',
    'EV3', 'EV5', 'EV6', 'EV9', 'Rondo', 'Cadenza', 'K900', 'Borrego', 'Ceed', 'Picanto', 'Stonic', 'XCeed'],
  'Koenigsegg': ['Jesko', 'Gemera', 'Regera', 'Agera'],
  'SsangYong': ['Torres', 'Korando', 'Rexton', 'Tivoli', 'Musso'],
  'Lada': ['Niva', 'Vesta', 'Granta', 'Largus'],
  'Lamborghini': ['Huracán', 'Temerario', 'Revuelto', 'Urus', 'Aventador'],
  'Lancia': ['Ypsilon', 'Delta'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque',
    'LR2', 'LR3', 'LR4', 'Freelander'],
  'Lexus': ['IS', 'ES', 'GS', 'LS', 'RC', 'LC', 'UX', 'NX', 'RX', 'RZ', 'GX', 'LX', 'TX', 'LM', 'CT', 'HS', 'SC'],
  'Lincoln': ['Corsair', 'Nautilus', 'Aviator', 'Navigator', 'MKZ', 'Continental', 'MKC', 'MKX', 'MKT', 'MKS', 'Town Car'],
  'Lotus': ['Emira', 'Eletre', 'Emeya', 'Evora', 'Exige', 'Elise'],
  'Lucid': ['Air', 'Gravity'],
  'Lynk & Co': ['01', '02', '08'],
  'Mahindra': ['Scorpio', 'XUV700', 'XUV300', 'Thar', 'Bolero'],
  'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'Grecale', 'MC20', 'GranTurismo', 'GranCabrio'],
  'Mazda': ['Mazda2', 'Mazda3', 'Mazda6', 'MX-5 Miata', 'MX-30', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-60', 'CX-70', 'CX-80', 'CX-90',
    'CX-7', 'CX-9', 'Mazda5', 'RX-8', 'Tribute'],
  'McLaren': ['Artura', '750S', '720S', 'GT', 'GTS', '570S', '600LT', 'W1'],
  'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLE', 'CLS', 'E-Class', 'S-Class', 'GLA', 'GLB', 'GLC', 'GLC Coupe', 'GLE', 'GLE Coupe',
    'GLS', 'G-Class', 'SL', 'AMG GT', 'EQA', 'EQB', 'EQE', 'EQE SUV', 'EQS', 'EQS SUV', 'Maybach S-Class', 'Sprinter', 'eSprinter',
    'Metris', 'Vito', 'GLK', 'ML', 'GL', 'SLK', 'SLC'],
  'Mercury': ['Milan', 'Mariner', 'Grand Marquis', 'Montego', 'Sable'],
  'MG': ['MG3', 'MG4', 'MG5', 'ZS', 'ZS EV', 'HS', 'Marvel R', 'Cyberster'],
  'MINI': ['Cooper', 'Cooper S', 'John Cooper Works', 'Countryman', 'Clubman', 'Paceman', 'Aceman', 'Convertible', 'Cooper SE'],
  'Mitsubishi': ['Mirage', 'Mirage G4', 'Lancer', 'Outlander', 'Outlander PHEV', 'Outlander Sport', 'RVR', 'Eclipse Cross', 'Pajero', 'Triton', 'i-MiEV', 'ASX'],
  'Nissan': ['Versa', 'Sentra', 'Altima', 'Maxima', 'Leaf', 'Ariya', '370Z', 'Z', 'GT-R', 'Kicks', 'Juke', 'Qashqai', 'Rogue', 'Rogue Sport',
    'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Titan', 'NV200', 'NV', 'Micra', 'Cube', 'Xterra', 'Quest', 'X-Trail', 'Navara'],
  'Opel': ['Corsa', 'Astra', 'Insignia', 'Mokka', 'Crossland', 'Grandland', 'Frontera', 'Zafira', 'Combo', 'Vivaro', 'Movano', 'Adam', 'Meriva'],
  'Pagani': ['Huayra', 'Zonda', 'Utopia'],
  'Peugeot': ['108', '208', 'e-208', '308', '408', '508', '2008', '3008', '5008', 'Rifter', 'Partner', 'Expert', 'Boxer', 'Traveller'],
  'Polestar': ['Polestar 1', 'Polestar 2', 'Polestar 3', 'Polestar 4'],
  'Pontiac': ['G5', 'G6', 'G8', 'Vibe', 'Grand Prix', 'Grand Am', 'Sunfire', 'Montana', 'Torrent', 'Solstice'],
  'Porsche': ['911', '718 Boxster', '718 Cayman', 'Taycan', 'Panamera', 'Macan', 'Macan Electric', 'Cayenne', 'Cayenne Coupe'],
  'Proton': ['Saga', 'Persona', 'X50', 'X70'],
  'Ram': ['1500', '1500 Classic', '2500', '3500', 'ProMaster', 'ProMaster City', 'Dakota'],
  'Renault': ['Clio', 'Captur', 'Megane', 'Megane E-Tech', 'Austral', 'Arkana', 'Espace', 'Scenic', 'Symbioz', 'Rafale', '5 E-Tech', 'Twingo', 'Zoe',
    'Kadjar', 'Koleos', 'Talisman', 'Kangoo', 'Trafic', 'Master'],
  'Rivian': ['R1T', 'R1S', 'R2', 'R3', 'EDV'],
  'Rolls-Royce': ['Ghost', 'Phantom', 'Cullinan', 'Spectre', 'Wraith', 'Dawn'],
  'Saab': ['9-3', '9-5', '9-7X'],
  'Saturn': ['Ion', 'Aura', 'Vue', 'Outlook', 'Sky', 'Astra'],
  'Scion': ['FR-S', 'iA', 'iM', 'iQ', 'tC', 'xB', 'xD'],
  'SEAT': ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco', 'Alhambra'],
  'Škoda': ['Fabia', 'Scala', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq', 'Elroq', 'Rapid', 'Yeti'],
  'smart': ['fortwo', 'forfour', '#1', '#3'],
  'Subaru': ['Impreza', 'WRX', 'BRZ', 'Legacy', 'Outback', 'Crosstrek', 'Forester', 'Ascent', 'Solterra', 'XV Crosstrek', 'Tribeca', 'Baja'],
  'Suzuki': ['Swift', 'Vitara', 'Grand Vitara', 'S-Cross', 'Jimny', 'Ignis', 'SX4', 'Kizashi', 'Across', 'Swace'],
  'Tata': ['Nexon', 'Punch', 'Harrier', 'Safari', 'Tiago'],
  'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X', 'Cybertruck', 'Roadster'],
  'Toyota': ['Yaris', 'Corolla', 'Corolla Hatchback', 'Corolla Cross', 'Camry', 'Crown', 'Crown Signia', 'Avalon', 'Prius', 'Prius Prime', 'Mirai',
    'GR86', '86', 'GR Corolla', 'GR Supra', 'C-HR', 'RAV4', 'RAV4 Prime', 'bZ4X', 'bZ', 'Venza', 'Highlander', 'Grand Highlander', '4Runner',
    'Sequoia', 'Land Cruiser', 'Tacoma', 'Tundra', 'Sienna', 'Matrix', 'FJ Cruiser', 'Echo', 'Celica', 'MR2', 'Hilux', 'Aygo X', 'Proace'],
  'Vauxhall': ['Corsa', 'Astra', 'Mokka', 'Frontera', 'Grandland', 'Combo', 'Vivaro', 'Movano'],
  'Volkswagen': ['Jetta', 'Jetta GLI', 'Golf', 'Golf GTI', 'Golf R', 'Golf Alltrack', 'Golf SportWagen', 'Passat', 'Arteon', 'Beetle', 'CC', 'Eos',
    'Taos', 'Tiguan', 'Atlas', 'Atlas Cross Sport', 'ID.3', 'ID.4', 'ID.7', 'ID. Buzz', 'Touareg', 'Polo', 'T-Roc', 'T-Cross', 'Touran',
    'Transporter', 'Crafter', 'Amarok', 'Caddy', 'Routan', 'Rabbit'],
  'Volvo': ['S60', 'S90', 'V60', 'V60 Cross Country', 'V90', 'V90 Cross Country', 'XC40', 'XC60', 'XC90', 'EX30', 'EX40', 'EX90', 'EC40',
    'C40 Recharge', 'C30', 'C70', 'S40', 'S80', 'V50', 'V70', 'XC70'],
}

export const MANUFACTURERS = Object.keys(VEHICLE_MODELS).sort((a, b) => a.localeCompare(b))

/** The models of a manufacturer, also when it was typed differently ("mercedes", "Mercedes Benz"); none for an unknown one. */
export function modelsOf(manufacturer: string | null | undefined): string[] {
  const key = normalize(manufacturer)
  if (!key) return []
  const match = MANUFACTURERS.find(m => normalize(m) === key) ?? MANUFACTURERS.find(m => normalize(m).startsWith(key) && key.length >= 4)
  return match ? [...VEHICLE_MODELS[match]].sort((a, b) => a.localeCompare(b, undefined, { numeric: true })) : []
}

function normalize(value: string | null | undefined): string {
  return (value ?? '').normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '')
}
