<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
	<PropertyGroup>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants)TRACE;MIGRATING_</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants)TRACE;MIGRATING_</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.4.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
    <PackageReference Include="NHibernate" Version="5.5.2" />
    <PackageReference Include="NHibernate.Driver.MySqlConnector" Version="2.0.5" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VgAuto.Core.Application\VgAuto.Core.Application.csproj" />
    <ProjectReference Include="..\VgAuto.Domain\VgAuto.Core.Domain.csproj" />
    <ProjectReference Include="..\VgAuto.Http.Api.Model\VgAuto.Http.Api.Model.csproj" />
  </ItemGroup>

</Project>
